version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: alura-api-rest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
